### ISSUE TITLE
Encounter an error

### ISSUE THREAD

**Issue by pcxdi** [sisinflab/personalized-popularity-awareness#1]
Hello, thank you for your contribution, I want to test your wonderful project, I followed your steps but encountered such errors, in addition, there are Yandex data sets I did not find online, as a beginner, I feel very confused, I hope you can answer me, I really hope to test your project, thank you
**fatal: Not a git repository (or any parent directory up to the mount point /)
Stop at the file system boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM is not set).
Traceback (most recent call last):
File "/home/as/ljj/personalized-popularity-awareness-main/evaluation/dataset_by_config.py", line 4, in <module>
spec = importlib.util.spec_from_file_location("config", sys.argv[1])
^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^
AttributeError: module 'importlib' has no attribute 'util'
running experiments on dataset
experement resutls are saved at ./results//_2024_10_01T14_26_32
cp: Missing target file to operate after './results//_2024_10_01T14_26_32'
Try executing "cp --help" for more information.
experiment_stdout: ./results//_2024_10_01T14_26_32/stdout
experiment_stderr: ./results//_2024_10_01T14_26_32/stderr
experiment_result: ./results//_2024_10_01T14_26_32/experiment_1.json
experiment_commit: ./results//_2024_10_01T14_26_32/commit
fatal: Not a git repository (or any parent directory up to the mount point /)
Stop at the file system boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM is not set).**

**Comment by davide-abbattista** [comment]
I've solved "AttributeError: module 'importlib' has no attribute 'util'" in the last commit. 
Yandex music event dataset should be downloaded manually from https://www.kaggle.com/competitions/yandex-music-event-2019-02-16 and put into data/yandex, as stated in datasets/yandex.py.

**Comment by davide-abbattista** [comment]
I've solved "_AttributeError: module 'importlib' has no attribute 'util'_" in the last commit.
Yandex music event dataset should be downloaded manually from https://www.kaggle.com/competitions/yandex-music-event-2019-02-16 and put into _data/yandex_, as stated in _datasets/yandex.py_.
